socialapps/socialapp2/config/routes.rb
Socialapp2::Application.routes.draw do

  resources :user_profiles

  devise_for :users

  root 'home#index'

end

socialapps/socialapp2/app/models/user.rb
class User < ActiveRecord::Base
	has_one :user_profile
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

socialapps/socialapp2/app/models/user_profile.rb
class UserProfile < ActiveRecord::Base
  belongs_to :user
  validates :profile_pic, :facebook, :twitter, presence: true
  validates :facebook, :twitter, uniqueness: true
end

socialapps/socialapp2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

socialapps/socialapp2/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

socialapps/socialapp2/app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_user_profile, only: [:show, :edit, :update, :destroy]

  # GET /user_profiles
  # GET /user_profiles.json
  def index
    @user_profiles = UserProfile.all
  end

  # GET /user_profiles/1
  # GET /user_profiles/1.json
  def show
  end

  # GET /user_profiles/new
  def new
    @user_profile = UserProfile.new
  end

  # GET /user_profiles/1/edit
  def edit
  end

  # POST /user_profiles
  # POST /user_profiles.json
  def create
    @user_profile = UserProfile.new(user_profile_params)
    @user_profile.user = current_user

    respond_to do |format|
      if @user_profile.save
        format.html { redirect_to @user_profile, notice: 'User profile was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user_profile }
      else
        format.html { render action: 'new' }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_profiles/1
  # PATCH/PUT /user_profiles/1.json
  def update
    respond_to do |format|
      if @user_profile.update(user_profile_params)
        format.html { redirect_to @user_profile, notice: 'User profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_profiles/1
  # DELETE /user_profiles/1.json
  def destroy
    @user_profile.destroy
    respond_to do |format|
      format.html { redirect_to user_profiles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_profile
      @user_profile = UserProfile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_profile_params
      params.require(:user_profile).permit(:user_id, :profile_pic, :facebook, :twitter)
    end
end

socialapps/socialapp2/app/helpers/application_helper.rb
module ApplicationHelper
end

socialapps/socialapp2/app/helpers/home_helper.rb
module HomeHelper
end

socialapps/socialapp2/app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

socialapps/socialapp2/app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

socialapps/socialapp2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Socialapp2</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

socialapps/socialapp2/app/views/user_profiles/_form.html.erb
<%= form_for(@user_profile) do |f| %>
  <% if @user_profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_profile.errors.count, "error") %> prohibited this user_profile from being saved:</h2>

      <ul>
      <% @user_profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :profile_pic %><br>
    <%= f.text_field :profile_pic %>
  </div>
  <div class="field">
    <%= f.label :facebook %><br>
    <%= f.text_field :facebook %>
  </div>
  <div class="field">
    <%= f.label :twitter %><br>
    <%= f.text_field :twitter %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

socialapps/socialapp2/app/views/user_profiles/edit.html.erb
<h1>Editing user_profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_profile %> |
<%= link_to 'Back', user_profiles_path %>

socialapps/socialapp2/app/views/user_profiles/index.html.erb
<h1>Listing user_profiles</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Profile pic</th>
      <th>Facebook</th>
      <th>Twitter</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @user_profiles.each do |user_profile| %>
      <tr>
        <td><%= user_profile.user %></td>
        <td><%= user_profile.profile_pic %></td>
        <td><%= user_profile.facebook %></td>
        <td><%= user_profile.twitter %></td>
        <td><%= link_to 'Show', user_profile %></td>
        <td><%= link_to 'Edit', edit_user_profile_path(user_profile) %></td>
        <td><%= link_to 'Destroy', user_profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User profile', new_user_profile_path %>

socialapps/socialapp2/app/views/user_profiles/new.html.erb
<h1>New user_profile</h1>

<%= render 'form' %>

<%= link_to 'Back', user_profiles_path %>

socialapps/socialapp2/app/views/user_profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_profile.user.email %>
</p>

<p>
  <strong>Profile pic:</strong>
  <%= image_tag @user_profile.profile_pic %>
</p>

<p>
  <strong>Facebook:</strong>
  <%= link_to "Facebook Link", @user_profile.facebook %>
</p>

<p>
  <strong>Twitter:</strong>
  <%= link_to @user_profile.twitter, "http://twitter.com/" + @user_profile.twitter %>
</p>

<%= link_to 'Edit', edit_user_profile_path(@user_profile) %> |
<%= link_to 'Back', user_profiles_path %>